### PR TITLE
updates for preview3

### PR DESCRIPTION
**Pull request by vhvb1989**
- updates for p3
- mob-project
- readme update for azd

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@vhvb1989 @BrennanConroy What should we do with this PR? Any parts we should keep or just close it?

**Comment by BrennanConroy** [comment]
Never saw this. The readme changes might be nice to keep, the rest doesn't look worth keeping (removing AppInsights? No thanks).

**Comment by adityamandaleeka** [comment]
I think we got the README changes separately since then

**Comment by adityamandaleeka** [comment]
OK, I'll close this. @vhvb1989 you're always welcome to reopen/open another of course :)

**Pull request closed without merging**
